from typing import Dict, List, Any, Optional

from UI.UI_Components import UIComponents
from UI.chat_interface import ChatInterface
from UI.sidebar import Sidebar
from UI.metrics_display import MetricsDisplay
from UI.flashcard_display import FlashcardDisplay
from models import Flashcard
from infrastructure.Common.rag_pipeline import RAGPipeline
from infrastructure.Common import RAG_Constants as constants
import Utils.Utils

class MainPage:
    """Main application page integrating all components"""
    
    def __init__(
        self
    ):
        """Initialize the main page with all required use cases"""
        
        # Initialize UI components
        self.initialize_components()
    
    def initialize_components(self):
        """Initialize all UI components"""
        UIComponents.initialize_page()
        # Chat interface
        self.chat_interface = ChatInterface(
            on_message_callback=None
        )
        
        # Sidebar component
        self.sidebar = Sidebar(
        )
        self.flashcard_display = FlashcardDisplay(
            flashcards=[] # Initially empty, will be populated from session state
        )
       
    def trigger_flashcard_generation(self):
        """Handles the flashcard generation process using RAGPipeline."""
        pipeline = Utils.Utils.get_pipeline() # Get the RAGPipeline instance
        if not pipeline or not hasattr(pipeline, 'generate_flashcards_from_text'):
            UIComponents.display_error("RAG Pipeline not available or misconfigured for flashcard generation.")
            UIComponents.set_session_state_variable("flashcards", [])
            UIComponents.set_session_state_variable("flashcards_generation_attempted", True)
            return

        # Attempt to get processed document content. 
        # This assumes 'processed_document_texts' is a list of strings (chunks/documents)
        # stored in session state after document processing via the sidebar/upload logic.
        # You might need to adjust this based on how your application stores processed text.
        docs_for_flashcards_content = UIComponents.get_session_state_variable("processed_document_texts", []) 

        if not docs_for_flashcards_content:
            UIComponents.display_warning("No processed document content available for flashcard generation. Please ensure documents are uploaded and processed first.")
        
        # Concatenate all document/chunk texts into a single string
        # Ensure docs_for_flashcards_content is a list of strings
        if isinstance(docs_for_flashcards_content, list) and all(isinstance(item, str) for item in docs_for_flashcards_content):
            full_text_content = "\n\n---\n\n".join(docs_for_flashcards_content)
        elif isinstance(docs_for_flashcards_content, str): # If it's already a single string
            full_text_content = docs_for_flashcards_content
        else:
            UIComponents.display_error("Document content for flashcards is in an unexpected format.")
            return

        if not full_text_content.strip():
            UIComponents.display_warning("No text content available to generate flashcards from.")
            UIComponents.set_session_state_variable("flashcards", [])
            UIComponents.set_session_state_variable("flashcards_generation_attempted", True)
            return

        with UIComponents.display_spinner("Generating flashcards..."):
            UIComponents.display_info("Generating flashcards... This may take a moment.")
            generated_flashcards = pipeline.generate_flashcards_from_text(full_text_content, num_flashcards=constants.NUM_OF_FLASHCARDS)
        
        UIComponents.set_session_state_variable("flashcards", generated_flashcards)
        UIComponents.set_session_state_variable("flashcards_generation_attempted", True)
        UIComponents.set_session_state_variable("card_index", 0)  # Reset index for new flashcards
        UIComponents.set_session_state_variable("show_answer", False)  # Reset answer visibility
        
        # Display success or warning based on generation result
        if generated_flashcards:
            UIComponents.display_success(f"{len(generated_flashcards)} flashcards generated successfully!")
        else:
            UIComponents.display_warning("No flashcards were generated by the LLM. The content might have been unsuitable or an error occurred.")

    def render(self):
        """Render the main page"""        
        # Render page title
        UIComponents.create_title("RAG Modular Application")
        
        # Render sidebar
        self.sidebar.render_sidebar()
        
        # Create main tabs
        tabs = UIComponents.create_tabs(["Chat", "Evaluation", "FlashCards", "Debug"])
        
        # Chat tab
        with tabs[0]:
            self.chat_interface.render()
        
        # Evaluation tab
        with tabs[1]:
            self.sidebar.render_evaluation_section()
            self.sidebar.render_evaluation_config()
        
        # Flashcards tab
        with tabs[2]:
            UIComponents.create_subheader_UI("Flashcard Generation & Review")

            if UIComponents.create_button("✨ Generate Flashcards"): 
                self.trigger_flashcard_generation()

            # Ensure session state keys exist before first use
            if "flashcards" not in UIComponents.get_session_state():
                 UIComponents.set_session_state_variable("flashcards", [])
            if "flashcards_generation_attempted" not in UIComponents.get_session_state():
                 UIComponents.set_session_state_variable("flashcards_generation_attempted", False)

            flashcards = UIComponents.get_session_state_variable("flashcards", [])
            flashcards_generation_attempted = UIComponents.get_session_state_variable("flashcards_generation_attempted", False)

            if not flashcards:
                if flashcards_generation_attempted:
                    UIComponents.display_info("No flashcards were generated. Try again or check your document source if applicable.")
                else:
                    UIComponents.display_info("Click 'Generate Flashcards' to create new flashcards.")
            else:
                # Update the existing flashcard_display instance with new/retrieved flashcards
                self.flashcard_display.flashcards = flashcards 
                # Initialize session state for card navigation (e.g., reset index if flashcards change)
                self.flashcard_display.initialze_session_state() 
                
                self.flashcard_display.display_card()
                self.flashcard_display.create_columns()
                self.flashcard_display.show_or_hide_answer()
        
        # Debug tab
        with tabs[3]:
            self.render_debug_tab()
    
    def render_debug_tab(self):
        """Render the debug tab with system information"""
        UIComponents.create_subheader_UI("Debug Information")
        
        with UIComponents.create_expander("Session State", expanded=False):
            UIComponents.write(UIComponents.get_session_state())
        
        UIComponents.write("Component Metrics")
        if hasattr(UIComponents.get_session_state(), "documents") and UIComponents.get_session_state_variable("documents", None):
            metrics = self.get_component_metrics()
            MetricsDisplay.display_pipeline_metrics(metrics)
        else:
            UIComponents.display_info("Process documents to view component metrics")
    
    # --- Component type getters ---
    def get_component_config(self, component_name: str) -> Dict[str, Any]:
        """Get configuration for a specific component"""
        return self.configuration_usecase.get_component_config(component_name)
    
    def get_component_metrics(self) -> Dict[str, Any]:
        """Get metrics for all components"""
        # This would be implemented to retrieve metrics from the RAG service
        # For now, return mock data
        pipeline = Utils.Utils.get_pipeline()
        return {
            constants.CONFIG_CHUNKER: pipeline.get_chunker_cost_and_time(),
            constants.CONFIG_EMBEDDER: pipeline.get_embedder_cost_and_time(),
            constants.CONFIG_RETRIEVER: pipeline.get_retriever_cost_and_time(),
            constants.CONFIG_RERANKER: pipeline.get_reranker_cost_and_time(),
            constants.CONFIG_EVALUATOR: pipeline.get_evaluator_cost_and_time(),
            constants.CONFIG_VECTOR_STORE: pipeline.get_vector_store_cost_and_time(),
            constants.CONFIG_LLM: pipeline.get_llm_service_cost_and_time()
        }