from abc import ABC, abstractmethod
from typing import List, Dict, Any, Tuple, Optional

class BaseEvaluator(ABC):
    """Base class for all RAG evaluation components."""

    @abstractmethod
    def evaluate(
        self, 
        question: str, 
        answer: str, 
        contexts: List[str], 
        ground_truths: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Evaluates the performance of a RAG system.

        Args:
            question (str): The input query or question.
            answer (str): The answer generated by the RAG system.
            contexts (List[str]): The list of retrieved context documents.
            ground_truths (Optional[List[str]]): A list of one or more reference answers considered to be correct.

        Returns:
            Dict[str, Any]: A dictionary containing the evaluation metrics.
        """
        pass

    @abstractmethod
    def get_cost_and_time_taken(self) -> Tuple[float, float]:
        """
        Returns the total cost and time taken for the evaluation process.

        Returns:
            Tuple[float, float]: A tuple containing the cost and time taken.
        """
        pass