# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyCFQ0VjGetLO0QoeZ5UMLOf6SvuduSeyzI"
OPEN_AI_API_KEY = "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"
